@url = http://localhost:5557

### GET JOBS
GET {{url}}/jobs

### GET ONE JOB
GET {{url}}/jobs/1

### POST JOB
POST {{url}}/jobs
content-type: application/json

{
	"jobTitle": "Vue.js Developer",
	"description": "Requires vue.js skills."
}

### DELETE JOB
DELETE {{url}}/jobs/3
